
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 6;
  public static final int STRING_LITERAL = 40;
  public static final int LPAREN = 7;
  public static final int INT = 17;
  public static final int PRINTLN = 24;
  public static final int MINUS = 4;
  public static final int RPAREN = 8;
  public static final int NOT = 36;
  public static final int CNAME = 14;
  public static final int SEMICOLON = 2;
  public static final int AND = 29;
  public static final int LT = 30;
  public static final int OR = 28;
  public static final int BOOL = 18;
  public static final int COMMA = 16;
  public static final int GET = 33;
  public static final int CLASS = 13;
  public static final int PLUS = 3;
  public static final int MAIN = 12;
  public static final int IF = 20;
  public static final int THIS = 41;
  public static final int DOT = 25;
  public static final int ID = 15;
  public static final int EOF = 0;
  public static final int RETURN = 27;
  public static final int EQUAL = 26;
  public static final int TRUE = 37;
  public static final int NEW = 42;
  public static final int error = 1;
  public static final int NULL = 43;
  public static final int DEQUAL = 34;
  public static final int VOID = 11;
  public static final int READLN = 23;
  public static final int TIMES = 5;
  public static final int LBRACE = 9;
  public static final int ELSE = 21;
  public static final int WHILE = 22;
  public static final int LET = 32;
  public static final int RBRACE = 10;
  public static final int STRING = 19;
  public static final int DIFF = 35;
  public static final int FALSE = 38;
  public static final int GT = 31;
  public static final int INTEGER_LITERAL = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "VOID",
  "MAIN",
  "CLASS",
  "CNAME",
  "ID",
  "COMMA",
  "INT",
  "BOOL",
  "STRING",
  "IF",
  "ELSE",
  "WHILE",
  "READLN",
  "PRINTLN",
  "DOT",
  "EQUAL",
  "RETURN",
  "OR",
  "AND",
  "LT",
  "GT",
  "LET",
  "GET",
  "DEQUAL",
  "DIFF",
  "NOT",
  "TRUE",
  "FALSE",
  "INTEGER_LITERAL",
  "STRING_LITERAL",
  "THIS",
  "NEW",
  "NULL"
  };
}

